name = "codesaviour-api"
main = "server/worker.js"
compatibility_date = "2024-01-01"

[env.production]
name = "codesaviour-api"

[[env.production.vars]]
FIREWORKS_BASE_URL = "https://api.fireworks.ai/inference/v1"
FIREWORKS_MODEL = "accounts/fireworks/models/qwen2p5-coder-32b-instruct"
OPENROUTER_BASE_URL = "https://openrouter.ai/api/v1"
OPENROUTER_MODEL = "qwen/qwen-2.5-coder-32b-instruct:free"
SITE_URL = "https://codesaviour.pages.dev"
SITE_TITLE = "CodeSaviour"

# Add your API keys as secrets using: wrangler secret put FIREWORKS_API_KEY
# wrangler secret put OPENROUTER_API_KEY