name: Vercel Deploy

on:
  push:
    branches: [ "cleanup-publish-ready", "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Vercel CLI
        run: npm i -g vercel

      - name: Pull Vercel Environment Info
        run: vercel pull --yes --environment=production --token=${{ env.VERCEL_TOKEN }}

      - name: Build
        run: vercel build --prod --token=${{ env.VERCEL_TOKEN }}

      - name: Deploy Prebuilt
        run: vercel deploy --prebuilt --prod --token=${{ env.VERCEL_TOKEN }}